// Tekst pomocy (78 znaków szerokoœci)
const char* txt_readme[] = {
  "Pomoc dla programu wspieraj¹cego powtarzanie wyra¿eñ w jêzykach obcych Englot",
  "© 2016-2017 Mateusz Karcz, PG ETI",
  "",
  "» Menu g³ówne «",
  "W dolnej czêœci ekranu znajduje siê pole 'Twój wybór'. Wpisz cyfrê przypisan¹",
  "danemu dzia³aniu i naciœnij klawisz ENTER w celu jego wykonania.",
  "",
  "» Test",
  "Jeœli wczeœniej wybrano s³ownik, to po wpisaniu cyfry 1 i naciœniêciu klawi-",
  "sza ENTER wyœwietli siê okno 'TEST WIEDZY'. Wpisz iloœæ wyra¿eñ, które chcesz",
  "powtórzyæ (minimum 5, po w pisaniu wartoœci wiêkszej ni¿ liczba wyra¿eñ",
  "w s³owniku program przepyta z ca³ego s³ownika). Po wpisaniu wartoœci i naciœ-",
  "niêciu klawisza ENTER pojawi siê komunikat",
  "'Wpisz polskie t³umaczenie wyra¿enia', a poni¿ej losowo wybrane wyra¿enie.",
  "Wpisz jego t³umaczenie w pole 'Twoja odpowiedŸ' i naciœnij klawisz ENTER.",
  "Jeœli Twoja odpowiedŸ oka¿e siê b³êdna, program poda poni¿ej poprawne t³uma-",
  "czenie. Nie ma mo¿liwoœci przerwania trwaj¹cego testu.",
  "Po zakoñczeniu testu tytu³ okna zmieni siê na 'KONIEC TESTU', a poni¿ej",
  "pojawi siê Twój wynik. Po naciœniêciu klawisza ENTER program wraca do g³ówne-",
  "go menu.",
  "",
  "» Moje statystyki",
  "Przy za³adowanym s³owniku po wpisaniu cyfry 2 (lub cyfry 1 bez s³ownika)",
  "i zatwierdzeniu jej klawiszem ENTER wyœwietli siê okno",
  "'STATYSTYKI U¯YTKOWNIKA'. Poni¿ej tytu³u, po lewej stronie zostanie wyœwiet-",
  "lony login, a po prawej pe³na nazwa zalogowanego u¿ytkownika.",
  "Poni¿ej tych danych zostanie wyœwietlona tabela zawieraj¹ca cztery kolumny —",
  "— datê i godzinê, nazwê s³ownika, wynik i wartoœæ procentow¹.",
  "Pod tabel¹ wyœwietla siê liczba rozwi¹zanych testów oraz ³¹czny wynik",
  "i procent obliczony z wszystkich ukoñczonych testów. Po naciœniêciu klawisza",
  "ENTER program wraca do g³ównego menu.",
  "",
  "» Wyniki wed³ug testów",
  "Przy za³adowanym s³owniku wybranie opcji 3 (lub odpowiednio 2 bez s³ownika)",
  "skutkuje wyœwietleniem okna 'RANKING TESTÓW'.",
  "W oknie tym znajduje siê tabela zawieraj¹ca piêæ kolumn — datê i godzinê,",
  "pe³n¹ nazwê u¿ytkownika, nazwê s³ownika, wynik i wartoœæ procentowê. Program",
  "wyœwietla wszystkie wyniki wszystkich u¿ytkowników posortowane wed³ug iloœci",
  "zdobytych punktów. Po naciœniêciu klawisza ENTER program wraca do g³ównego",
  "menu.",
  "",
  "» Wyniki wed³ug u¿ytkowników",
  "Po wybraniu opcji 4 (lub 3 bez wybranego s³ownika) program wyœwietli okno",
  "'RANKING U¯YTKOWNIKÓW'. Znajdzie siê w nim tabela zawieraj¹ca trzy kolumny —",
  "— nazwê u¿ytkownika, liczbê wszystkich jego testów i zdobytych przez niego",
  "punktów, które stanowi¹ równie¿ kryterium sortowania tej tabeli.",
  "Po naciœniêciu klawisza ENTER program wraca do g³ównego menu.",
  "",
  "» Wybór s³ownika",
  "Jeœli nie wybrano wczeœniej s³ownika, to po wpisaniu cyfry 4 i naciœniêciu",
  "klawisza ENTER wyœwietli siê okno 'WYBÓR S£OWNIKA' z komunikatem",
  "'Wpisz nazwê pliku s³ownika'. W przypadku, gdy s³ownik zosta³ ju¿ wczeœniej",
  "wczytany, to cyfra 5 jest przypisana tej akcji.",
  "Wpisz nazwê pliku s³ownika i naciœnij klawisz ENTER. Zostanie wyœwietlony",
  "komunikat 'Otwarto s³ownik <nazwa s³ownika>'. Po naciœniêciu klawisza ENTER",
  "program wraca do g³ównego menu. Przy nazwie czynnoœci numer 5 zostanie wyœ-",
  "wietlona nazwa wybranego s³ownika.",
  "",
  "» Pomoc",
  "Po wpisaniu cyfry 6 (lub 5, gdy nie za³adowano s³ownika) i naciœniêciu klawi-",
  "sza ENTER wyœwietli siê obecne okno 'POMOC'. Naciœniêcie klawisza ENTER po-",
  "skutkuje przewiniêciem tekstu o jedn¹ linijkê. Po odczytaniu ca³oœci dokumen-",
  "tacji i naciœniêcie klawisza ENTER program wraca do g³ównego menu.",
  "",
  "» Wyloguj",
  "Po wpisaniu cyfry 9 i naciœniêciu klawisza ENTER wyœwietli siê okno",
  "'LOGOWANIE I REJESTRACJA'. W zale¿noœci od ¿¹danej czynnoœci proszê wpisaæ",
  "L (zaloguj) lub N (utwórz nowe konto). Po wpisaniu odpowiedniej litery i na-",
  "ciœniêciu klawisza ENTER zostanie wyœwietlony formularz logowania",
  "lub rejestracji. Proszê go wype³niæ zgodnie z upodobaniem, po czym nacisn¹æ",
  "klawisz ENTER skutkuj¹cy wyœwietleniem okna 'MENU G£ÓWNE'.",
  "",
  "» Zakoñcz",
  "Po wpisaniu cyfry 0 i naciœniêciu klawisza ENTER wyœwietl¹ siê dane twórcy",
  "programu. Po przeczytaniu i naciœniêciu klawisza ENTER program zostanie",
  "zakoñczony.",
  "",
  "",
  "» Pliki danych programu «",
  "Program wspieraj¹cy powtarzanie wyra¿eñ w jêzykach obcych Englot dzia³a",
  "na danych zawartych w plikach. Poni¿ej znajduje siê ich krótki opis.",
  "",
  "» Pliki s³ownika [*.CSV] (domyœlnie)",
  "Plikami s³ownika nazywa siê ka¿dy plik tekstowy systemu Windows, w którym",
  "w kolejnych liniach wystêpuj¹: jako pierwsze wyra¿enie w jêzyku obcym,",
  "po œredniku jego polskie t³umaczenie. Ka¿de kolejne has³o s³ownika",
  "zaczyna siê od nowej linii.",
  "Jeœli pierwsza linia pliku rozpoczyna siê sekwencj¹ '#;', to tekst po œred-",
  "niku stanowi tytu³ s³ownika.",
  "",
  "» Pliki indeksu [*.IND]",
  "Plik indeksu jest tworzony dla ka¿dego pliku s³ownika. Jest on plikiem binar-",
  "nym zawieraj¹cym po³o¿enia kolejnych hase³ w pliku s³ownika.",
  "",
  "» Plik zapisu [ENGLOT.DAT]",
  "W pliku Englot.dat przy zamykaniu programu zapisywane s¹ wszystkie dane",
  "o u¿ytkownikach, testach i wynikach. S¹ one wczytywane przy kolejnym urucho-",
  "mieniu programu.",
  "",
  "» Plik dziennika [ENGLOT.LOG]",
  "W pliku tekstowym Englot.log zapisywane s¹ techniczne komunikaty opisuj¹ce",
  "przebieg dzia³ania danej sesji programu.",
  "",
  "© pomoc: Marta Kaczor",
  nullptr
};
